[profile.default]
extends = "../../foundry-base-config.toml"
prompt_timeout = 120
# Enables to use python scripts in forge tests.
ffi = true
gas_reports = ["Votemarket"]

[profile.ci]
extends = "../../foundry-base-config.toml"
