[profile.default]
src = "src"
out = "out"
libs = ["node_modules"]
solc = "0.8.19"

# Enables to use python scripts in forge tests.
ffi = true
fs_permissions = [{ access = "read-write", path = "./"}]

verbosity = 3
optimizers_runs = 200

gas_reports = [
"Votemarket"
]

[fuzz]
max_test_rejects = 1_000_000 # Number of times `vm.assume` can fail




[etherscan]

unknown_chain = { key = "${TENDERLY_ACCESS_KEY}", chain = 1, url = "${TENDERLY_VIRTUAL_TESTNET_RPC}/verify/etherscan" }

[rpc_endpoints]
bnb = "https://rpc.ankr.com/bsc"
frax = "https://frax-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
base = "https://base-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
arbitrum = "https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
optimism = "https://opt-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
zksync = "https://zksync-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
polygon = "https://polygon-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
polygonzkevm = "https://polygonzkevm-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"