name: Votemarket - Gas Comparison

env:
  FOUNDRY_PROFILE: "ci"
  ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
  MNEMONIC: ${{ secrets.MNEMONIC }}

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

# This CI workflow is responsible of running the gas comparison for the votemarket package.
# It is triggered
# - only when the changes are made to the votemarket package or the address-book package
# - when a PR is opened or when a push is made to the main branch
# - when a PR is opened or when a push is made to the feat/onlyboost-v2 branch
# - when the workflow is manually triggered
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "packages/votemarket/**"
      - ".github/workflows/votemarket_gas-diff.yml" # this file
      - "packages/utils/**" # dependency
      - "packages/periphery/**" # dependency
    branches:
      - main
      - develop
  push:
    paths:
       - "packages/votemarket/**"
       - ".github/workflows/votemarket_gas-diff.yml" # this file
       - "packages/utils/**" # dependency
       - "packages/periphery/**" # dependency
    branches:
      - main

jobs:
  compare_gas:
    runs-on: ubuntu-latest

    permissions:
      contents: write # to upload the gas report as artifact
      actions: read # to read the artifacts uploaded by another branch
      pull-requests: write # to post a comment on the PR

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.4
          cache: "pnpm"

      - name: Install node dependencies
        run: pnpm install

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install python dependencies
        working-directory: packages/votemarket
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

        # the seed changes weekly to avoid burning through RPC allowance
      - name: Generate the weekly fuzz seed
        run: >
          echo "FOUNDRY_FUZZ_SEED=$(
            echo $(($EPOCHSECONDS - $EPOCHSECONDS % 604800))
          )" >> $GITHUB_ENV

      - name: Run snapshot on unit tests
        working-directory: packages/votemarket
        # store the gas report in the root of the repository
        run: forge test --gas-report > ../../gasreport.ansi

      - name: Compare gas reports
        uses: Rubilmax/foundry-gas-diff@v3
        with:
          summaryQuantile: 0.9 # only display the 10% most significant gas diffs in the summary (defaults to 20%)
          sortCriteria: avg,max # sort diff rows by criteria
          sortOrders: desc,asc # and directions
          ignore: test-foundry/**/* # filter out gas reports from specific paths (test/ is included by default)
        id: gas_diff

      - name: Add gas diff to sticky comment
        if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: votemarket
          # delete the comment in case changes no longer impact gas costs
          delete: ${{ !steps.gas_diff.outputs.markdown }}
          message: ${{ steps.gas_diff.outputs.markdown }}
